# Generated by Django 3.1.5 on 2021-01-30 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginlog',
            old_name='datetime',
            new_name='datetimeLog',
        ),
        migrations.RenameField(
            model_name='loginlog',
            old_name='user',
            new_name='userLog',
        ),
    ]
