# Generated by Django 3.1.5 on 2021-01-31 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210130_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlog',
            name='changePass',
            field=models.TextField(blank=True, default=''),
        ),
    ]
