# Generated by Django 3.1.5 on 2021-02-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20210131_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroptions',
            name='changePassCode',
            field=models.TextField(blank=True, default='', max_length=35),
        ),
    ]
